# Docker
- task: ECRPullImage@1
  inputs:
    awsCredentials: 'AWSCris'
    regionName: 'us-east-2'
    repository: 'Craldo'
    imageSource: 'imagetag'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/KodotiAzureDevOps.Api/Dockerfile'
        tags: |
          $(tag)
